### ISSUE TITLE
The Legend of Zelda Vertical Dotted Lines

### ISSUE THREAD

**Issue by codyjarvis** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#124] opened 2021-04-30 19:26 UTC
Vertical dotted lines appear on screen when playing two separate copies of The Legend of Zelda.
Firmware: Nt-Mini-Noir-Jailbreak v6.6
Game: The Legend of Zelda - NES-ZL-0 PRG
Issue: Vertical dotted lines.

Tests/attempted fixes:
Cleaned both carts and tested continuity. Visually everything looks great.
Tested both carts on original hardware with no issues.
Dumped roms using copy nes. Roms looked great - no vertical dotted lines.
Flashed original firmware to Nt-Mini. Vertical lines no longer appear.

**Comment by codyjarvis** [comment] 2021-04-30 19:42
Also attempted with dejitter both on and off in case the issue was related to issue #95

**Comment by PizzaCube** [comment] 2021-05-07 17:50
my gold and grey cart does not have this issue so i am not sure why yours does.

**Comment by codyjarvis** [comment] 2021-06-09 00:16
@brym103 do the vertical lines disappear on the stock firmware? Mine do

**Comment by brym103** [comment] 2021-06-09 01:40
> @brym103 do the vertical lines disappear on the stock firmware? Mine do

Just tested -- no, I get the same issue when I flash back to the stock version 1.2 firmware.

**Comment by brym103** [comment] 2021-06-09 16:36
Update - I do NOT get the issue when I reverted to the stock version 1.1 firmware.  The cart plays perfectly on version 1.1.  I'm going to post this as a separate issue, but note that it may be a similar issue as this one.

**Comment by tjanas** [comment] 2021-06-09 16:47
Have you contacted Analogue directly and via Twitter? Something like this should be brought to their attention.

**Comment by brym103** [comment] 2021-06-09 16:53
> Have you contacted Analogue directly and via Twitter? Something like this should be brought to their attention.

I have not.  I was under the impression that posting issues here was the best way for the right people at Analogue to see them.  Is that not the case?

**Comment by tjanas** [comment] 2021-06-09 16:55
Perhaps the jailbreaker looks here from time to time, but this is not official by any means. Problems with official firmware and carts should definitely be brought to the attention of Analogue on Twitter, especially since it would pertain to their public relations and claims of perfection. Perhaps other users on Twitter with these issues could also chime in.

**Comment by tjanas** [comment] 2021-06-09 16:57
I think bringing it up on Twitter would help light a fire under Analogue's support teams and help direct their priorities to fixing issues like these (they may be unaware of all of these issues).

**Comment by brym103** [comment] 2021-06-09 17:04
Fair enough; I'll send a tweet their way.

**Comment by whitezombie2000** [comment] 2022-02-13 22:11
I cannot reproduce this issue with a real cartridge. I tested a gold Rev A copy of Zelda on the 6.6 JB and 1.2 firmware. Plays fine for me and so does the dumped ROM.

**Comment by tjanas** [comment] 2022-02-14 00:55
I’m confused why many people have experienced this issue while others have not with JB6.6. I don’t recall these issues reported with JB6.5. Are we sure it should be closed?

**Comment by whitezombie2000** [comment] 2022-02-14 02:02
Here's my cart of Zelda. I can't believe that battery still works. I need to replace that soon!

![Zelda](https://user-images.githubusercontent.com/23583562/153787561-3f38b3b2-a669-4bc4-a761-401beed282b9.JPG)

**Comment by tjanas** [comment] 2022-02-14 15:32
My battery (and save file) on my Zelda 1 cart from 30+ years ago are still working too. :) Those Maxell batteries were great.

**Comment by cizzymac** [comment] 2022-12-08 04:47
Leaving a comment here to advise that I receive the same issue with vertical dotted lines with my Everdrive N8 Rev 1.4, as well as my official Metroid Rev A cart, on JB 6.6. Flashed my Noir to official firmware 1.2 and get the same issue. Flashed to 1.1 and the lines are gone. Reflashed Noir with JB 6.6 without disturbing my seated Everdrive cart and the vertical dotted lines have returned. This is definitely a firmware issue causing this problem.

**Comment by tjanas** [comment] 2022-12-08 13:03
@cizzymac Please contact Analogue support to encourage them to release an update, and it wouldn’t hurt to let them know on Twitter too.

**Comment by tjanas** [comment] 2022-12-08 13:05
Have you tried flashing to JB 6.5? That seems to be the best fw at this point.

**Comment by cizzymac** [comment] 2022-12-08 15:20
@tjanas I did reach out to Analogue both via Twitter and via their support email on their website. It will be a shame to lose out on the fixes provided on 6.6, but I'll give 6.5 a shot today and see how it goes. Thanks much for your prompt response!

**Comment by tjanas** [comment] 2023-05-04 19:48
@cizzymac @codyjarvis please re-test your cartridges with the latest official firmware update released today https://www.analogue.co/support/nt-mini-noir/firmware/1.3

**Comment by cizzymac** [comment] 2023-05-04 19:49
@tjanas I can confirm the issue is resolved with the new official firmware on my end.

**Closed** 2023-05-04 20:05 UTC
Labels: needs confirmation, original cartridge

**Comment by whitezombie2000** [comment] 2023-05-04 21:21
@tjanas Should this be closed yet? The OP has not confirmed if their copy of Zelda is working. @cizzymac Never reported an issue with Zelda. Or can @cizzymac confirm that Zelda was an issue before and is working now.

**Comment by tjanas** [comment] 2023-05-05 02:57
@codyjarvis could you test please?

**Comment by cizzymac** [comment] 2023-05-05 05:53
@whitezombie2000 My issue was with Everdrive N8 1.3 and Metroid. I do not have a LoZ cart to test for you unfortunately.

**Comment by codyjarvis** [comment] 2023-05-05 12:18
I can load the new firmware and test this weekend.

**Comment by whitezombie2000** [comment] 2023-05-13 15:16
@codyjarvis How did the test go?
