### ISSUE TITLE
NES core audio peaks at -20db

### ISSUE THREAD

**Issue by Sean-Spicer** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#106] opened 2021-03-09 04:15 UTC
Default audio is too quiet, which isn't inline with other consoles and leads to more noise when correcting in amplification.

It should peak at -4db instead.

**Comment by tjanas** [comment] 2021-03-09 05:40
Duplicate of https://github.com/SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak/issues/102

**Closed by tjanas** 2021-03-09 05:40 UTC
Labels: duplicate
