### ISSUE TITLE
Rygar Cart - Vertical dotted lines on jb 6.6 firmware and stock version 1.2 firmware, but works fine on stock 1.1 fw

### ISSUE THREAD

**Issue by brym103** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#142] opened 2021-06-09 16:42 UTC
When playing my Rygar cart, I am getting dotted vertical lines on the screen similar to what are described on Zelda in issue #124.  I get this issue when using both the jb 6.6 firmware and the stock 1.2 firmware.  The cartridge has been thoroughly cleaned.  

When using copyNES mini on the jb 6.6 firmware, I was able to dump a ROM that works perfectly on the jb 6.6 firmware.  The MD5 checksum for the rom matches the known good dump of Rygar (USA) (Rev 1).nes (after stripping the header).  

I reverted to the stock version 1.1 firmware, and the cart works perfectly there.

**Comment by cmcginty** [comment] 2021-06-26 21:25
Also confirmed with Castlevania original cart. After downgrading to jb 6.5 the vertical lines are no longer visible. I did not attempt to dump the ROM to verify, but will be happy to if necessary.

**Comment by whitezombie2000** [comment] 2022-02-13 21:02
I cannot reproduce this issue with a real cartridge of Castlevania and Rygar on the official 1.2 firmware or the 6.6 JB firmware. It should be noted that my Castlevania is Rev A as stated on the back of the cartridge and Rygar is not Revision A.  I can dump both carts with CopyNES using mapper UxROM.BIN, load both dumped ROMS with out issue on the 6.6 JB firmware and on an emulator.

**Comment by tjanas** [comment] 2022-02-14 00:58
@brym103 which Rygar cart do you have? Is it the original (https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1874) with “ NES-RY-0 PRG” on the ROM chip inside the cart, or the revision cart with “NES-RY-1 PRG” on the ROM chip?

**Comment by tjanas** [comment] 2022-02-14 01:01
@cmcginty if you open your Castlevania cart, which ROM chip is it? “NES-CV-0 PRG” or “NES-CV-1 PRG” ?

**Comment by tjanas** [comment] 2022-02-14 01:07
![AC257403-8B68-44FD-9E56-B554297EB628](https://user-images.githubusercontent.com/20304619/153784096-02e8cc1c-a56c-45c0-ac1b-4c85fce59eb2.jpeg)
![8039F21E-0FDC-4B90-92BF-3ABBA9F0143A](https://user-images.githubusercontent.com/20304619/153784097-63b3bfec-0154-4475-9f1b-fea38da8bbd9.jpeg)

**Comment by brym103** [comment] 2022-02-14 01:09
@tjanas I don't have the tool needed to open the cart at the moment, but when I dumped the rom, it matched the checksum for this version after I removed the headers:
https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1875

For what it's worth, I eventually reported this issue directly to analogue support (maybe in September?) and they told me that they were aware of the issue and it would be fixed in the next firmware update.  Of course, who knows when that will be.

**Comment by tjanas** [comment] 2022-02-14 01:11
This issue should remain open until at least the release of JB6.7 or newer.

**Comment by whitezombie2000** [comment] 2022-02-14 01:24
Here's mine.

![Rygar](https://user-images.githubusercontent.com/23583562/153785073-1de22de0-76e8-4fe0-b29a-f572960fe328.JPG)

**Comment by tjanas** [comment] 2022-02-14 01:29
@whitezombie2000 I highly encourage you to submit that dump and PCB photo to no-intro, especially since they don’t have any photos for the initial version of Rygar. Or I can reach out to a No-Intro member to have your verification and photo(s) added on your behalf.

https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1874

https://forum.no-intro.org/

**Comment by whitezombie2000** [comment] 2022-02-14 01:34
Here's my Castlevania 1 cart.

![Castlevania](https://user-images.githubusercontent.com/23583562/153785696-573b4283-da74-44f1-beb7-74e7be920274.JPG)

**Comment by tjanas** [comment] 2022-02-14 01:47
I see that is a very late (1989) CV1 cart. You should submit scans of that one too

**Comment by whitezombie2000** [comment] 2022-02-14 02:17
@tjanas You can reach out to them if you want too. I will provide the two dumps here and delete them after you grab them.

[Files.zip](https://github.com/SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak/files/8057396/Files.zip)

**Comment by cmcginty** [comment] 2022-02-14 06:09
> @cmcginty if you open your Castlevania cart, which ROM chip is it? “NES-CV-0 PRG” or “NES-CV-1 PRG” ?

NES-CV-1 PRG
The chrram is a SHARP LH5164D3-L ... all on a NES-UN-ROM-07 PCB.

**Comment by tjanas** [comment] 2022-02-14 15:18
@whitezombie2000 your dumps and PCB photos have been passed along to a no-intro dumper and submitted.

**Comment by tjanas** [comment] 2022-02-21 02:50
@whitezombie2000 I have been informed they are now part of the No-Intro dat, credited to you:

https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1874

https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=0358

**Comment by ManeFunction** [comment] 2022-10-20 21:37
I assume, this is the same issue: https://github.com/SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak/issues/148

**Comment by brym103** [comment] 2022-10-21 15:09
> I assume, this is the same issue: #148

Looks like it to me, yes.

**Comment by cizzymac** [comment] 2022-12-08 04:54
Just leaving a comment here as well that I am receiving the same exact issue with my Everdrive N8 Rev 1.4 and my Metroid Rev A cart. Vertical, dotted lines persist on JB 6.6, official 1.2 firmware, and are resolved with official 1.1 firmware.

**Comment by tjanas** [comment] 2023-05-04 19:12
@cmcginty @cizzymac @brym103 please re-test with today’s firmware update.

**Comment by brym103** [comment] 2023-05-04 19:32
> @cmcginty @cizzymac @brym103 please re-test with today’s firmware update.

Oh I sold my NT Mini Noir to get a MiSTer like 15 months ago at this point.  I wasn't going to wait around for an indeterminate amount of time for a bug fix when it had already been a year.  The release notes for 1.3 indicate that it was supposed to fix my issue though:

>Fixed Vertical Green Lines in games using CHR-RAM (Castlevania, Legend of Zelda, Mega Man 1 & 2, Rygar, many others)

Hopefully it worked for those of you still in the Analogue ecosystem.

**Comment by cizzymac** [comment] 2023-05-04 19:48
I can confirm the issue with vertical dotted lines on my flash cart and official Metroid cart are now FIXED with the new official firmware! Hopefully we get an updated JB firmware soon, so this issue can be put to bed once and for all!

**Closed** 2023-05-04 20:06 UTC
Labels: bug, needs confirmation, original cartridge, PleaseContactAnalogue
